#!/bin/sh

set -x
set -e

if ! [ -r /srv/repository/conf/distributions ] ; then
  echo "Error: could not read /srv/repository/conf/distributions." >&2
  exit 1
fi

if [ "$#" -lt 1 ] ; then
  echo "Usage: $0 <codename>" >&2
  exit 1
fi

# repository/codename that should be added
REPOS="$1"

if [ -r /etc/jenkins/debian_glue ] ; then
  echo "*** Sourcing /etc/jenkins/debian_glue ***"
  . /etc/jenkins/debian_glue
fi

# support setting key id
if [ -z "${KEY_ID:-}" ] ; then
  echo "*** WARNING: No KEY_ID found, can not sign repository. ***"
  echo "***          Please set up /etc/jenkins/debian_glue, see"
  echo "***          /usr/share/jenkins-debian-glue/examples/debian_glue"
fi

if grep -q "^Codename: ${REPOS}$" /srv/repository/conf/distributions ; then
  echo "Codename/repository $REPOS exists already, ignoring request to add again."
  exit 0
fi

cat >> /srv/repository/conf/distributions << EOF

Codename: ${REPOS}
AlsoAcceptFor: unstable
Architectures: amd64 i386 source
Components: main
DebIndices: Packages Release . .gz
DscIndices: Sources Release .gz
Tracking: minimal
EOF

if [ -n "${KEY_ID:-}" ] ; then
  echo "*** Signing repository with Key ID $KEY_ID ***"
  printf "SignWith: ${KEY_ID}\n\n" >> /srv/repository/conf/distributions
fi

echo "Added $REPOS as new codename/repos to the reprepro configuration."
