#!/bin/sh

set -u

if [ "$#" -lt 1 ] ; then
  echo "Usage: $0 <version_number>" >&2
  exit 1
fi

PREVIOUS_VERSION="$1"

if echo "$PREVIOUS_VERSION" | grep -q -- '-[[:digit:]]*+' ; then
  echo "${PREVIOUS_VERSION}+1"
  exit 0
fi

# Debian version string present?
if ! echo $PREVIOUS_VERSION | grep -q -- '-' ; then
  LAST_PART="-1"
else
  BASE_VERSION=$(echo ${PREVIOUS_VERSION} | sed 's/\(~.*\)\|\(+.*\)$//')
  LAST_PART=$(echo $BASE_VERSION | sed 's/.*\-\([0-9]*\)$/\1/')
  LAST_PART=$(($LAST_PART + 1))
  PREVIOUS_VERSION="$(echo $PREVIOUS_VERSION | sed 's/^\(.*\)-.*$/\1/')-"
fi

echo "${PREVIOUS_VERSION}${LAST_PART}"
