#!/bin/sh

set -u

if [ "$#" -lt 1 ] ; then
  echo "Usage: $0 <version_number>" >&2
  exit 1
fi

PREVIOUS_VERSION="$1"

# remove Debian parts of version number (-1*, ~1*)
BASE_VERSION=$(echo ${PREVIOUS_VERSION} | sed 's/\(-.*\)\|\(~.*\)$//')

# if a Debian version is present, then use '-1' inside snapshot version
DEBIAN_VERSION=''
if echo $PREVIOUS_VERSION | grep -q -- '-' ; then
  DEBIAN_VERSION='-1'
fi

if ! echo "$PREVIOUS_VERSION" | grep -q -- '\.' ; then
  FIRST_PART="$PREVIOUS_VERSION"
  LAST_PART=""
else
  # first part of version number (0.9.2 -> 0.9)
  FIRST_PART=$(echo $BASE_VERSION | sed 's/\(\.[0-9]*\)$//')

  # last digit(s) of version number (0.9.2 -> 2)
  LAST_PART=$(echo $BASE_VERSION | sed 's/.*\.\([0-9]*\)$/\1/')
fi

## raise version number (2 -> 3)
# 0.9.0 -> 0.9.1
if echo "$LAST_PART" | grep -q -- '^0$' ; then
  RAISE_VERSION=$((LAST_PART + 1))
# 0.9.00 -> 0.9.01
elif echo "$LAST_PART" | grep -q -- '^0' ; then
  RAISE_VERSION="0$((LAST_PART + 1))"
# 0.8 -> 0.9
else
  RAISE_VERSION=$((LAST_PART + 1))
fi

# concat first part and raised version number (0.9.3)
INCR_VERSION="${FIRST_PART}.${RAISE_VERSION}"

echo "${INCR_VERSION}${DEBIAN_VERSION}"
