#!/bin/sh

SCRIPT=./scripts/jdg-increase-version-number

testEquality()
{
  assertEquals "$($SCRIPT 0.23)"       0.23+0
  assertEquals "$($SCRIPT 23)"         23+0
  assertEquals "$($SCRIPT 0.23-1)"     0.23-1+0
  assertEquals "$($SCRIPT 0.1.23-1)"   0.1.23-1+0
  assertEquals "$($SCRIPT 0.1.23-3)"   0.1.23-3+0
  assertEquals "$($SCRIPT 1:0.42-2)"   1:0.42-2+0
  assertEquals "$($SCRIPT 2008.01.02)" 2008.01.02+0
  assertEquals "$($SCRIPT 0.42~2)"     0.42~2+0
  assertEquals "$($SCRIPT 0.9.0)"      0.9.0+0
  assertEquals "$($SCRIPT 0.9.00)"     0.9.00+0
  assertEquals "$($SCRIPT 0.8)"        0.8+0
  assertEquals "$($SCRIPT 0.9)"        0.9+0
  assertEquals "$($SCRIPT 3.1.4+1)"    3.1.4+1+0
}

. /usr/share/shunit2/shunit2

# vim:foldmethod=marker ts=2 ft=sh ai expandtab sw=2
