#!/bin/bash

set -x
set -e

apt-ftparchive packages . | gzip > Packages.gz
apt-ftparchive contents . > Contents
cat <<EOF >Release
Origin: Jenkins Debian Glue Autobuild
Label: Jenkins Debian Glue Autobuild
NotAutomatic: yes
EOF
apt-ftparchive release . >> Release

# vim:foldmethod=marker ts=2 ft=sh ai expandtab sw=2
